name: terraform CICD
on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main 

  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  terraform_validation:
    name : Terraform Validation
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: environments/dev
    steps:
      #step 1: checkout terraform repositories
      - name: Checkout repository
        uses: actions/checkout@v4

      #step 2: Install required terraform version
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"
      
      #step 3: check terraform formatting
      - name: Terraform format check
        run: terraform fmt -check -recursive

      #Step 4: azure login
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      #step 5: initialize terraform 
      - name: initialize Terraform
        run: terraform init -backend=false

      #step 6: validate terraform configuration
      - name: Terraform validation 
        run: terraform validate

      #step 7: terraform execution plan
      - name: Terraform execution plan
        run: terraform plan -out=tfplan



  

  
