name: terraform CICD
on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main 

  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform_validation:
    name : Terraform Validation
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: environments/dev
    steps:
      #step 1: checkout terraform repositories
      - name: Checkout repository
        uses: actions/checkout@v4

      #step 2: Install required terraform version
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"
      
      #step 3: check terraform formatting
      - name: Terraform format check
        run: terraform fmt -check -recursive

      #step 4: initialize terraform 
      - name: initialize Terraform
        run: terraform init -backend=false

      #step 5: validate terraform configuration
      - name: Terraform validation 
        run: terraform validate



  

  
