name: terraform CICD
on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main 

  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  terraform_plan:
    name : Terraform plan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: environments/dev
    steps:
      #step 1: checkout terraform repositories
      - name: Checkout repository
        uses: actions/checkout@v4

      #step 2: Install required terraform version
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"
      
      #step 3: check terraform formatting
      - name: Terraform format check
        run: terraform fmt -check -recursive

      #Step 4: azure login
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      #step 5: initialize terraform 
      - name: initialize Terraform
        run: terraform init 

      #step 6: validate terraform configuration
      - name: Terraform validation 
        run: terraform validate

      #step 7: terraform execution plan
      - name: Terraform execution plan
        run: terraform plan -out=tfplan

      #step 8: Upload Terraform Plan
      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: environments/dev/tfplan
          if-no-files-found: error

  terraform_apply:
    name: Terraform Apply
    needs: terraform_plan
    runs-on: ubuntu-latest
    environment: dev

    defaults:
      run:
        working-directory: environments/dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Initialize Terraform
        run: terraform init 

      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan
          path: environments/dev

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan



  

  
